# .github/workflows/build.yml

name: Build Paimon Desktop Pet

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install
      run: |
        pip install -r requirements.txt
        pip install pyinstaller


    - name: Build EXE
      run: |
        pyinstaller ^
          --name PaimonDesktopPet ^
          --windowed ^
          --onefile ^
          main.py


    - name: Copy Assets
      run: |
        mkdir dist\assets
        copy assets\pet.png dist\assets\pet.png


    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: PaimonDesktopPet
        path: dist
