name: Build Paimon Desktop Pet

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"


    - name: Install requirements
      run: |
        pip install -r requirements.txt


    - name: Build EXE
      run: |
        pyinstaller --name PaimonDesktopPet --onefile --windowed main.py


    - name: Prepare Assets
      run: |
        mkdir dist\assets
        copy assets\pet.png dist\assets\pet.png
        xcopy assets\animations dist\assets\animations /E /I


    - name: Package
      run: |
        Compress-Archive -Path dist\* -DestinationPath PaimonDesktopPet.zip


    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PaimonDesktopPet
        path: PaimonDesktopPet.zip
